version: "3.6"
services:
  app:
    build: .
    ports:
      - 3333:3333
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
