version: "3.6"
services:
  service:
    build: ../tree-angular/
    ports:
      - 4200:4200
    depends_on:
      - app
  app:
    build: .
    ports:
      - 3333:3333
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tree
    ports:
      - 5432:5432
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
volumes:
  db-data:
